import { NextRequest, NextResponse } from "next/server";
import { readFile } from "fs/promises";
import os from "os";
import path from "path";

const SAFE_NAME = /^resume-\d+-[a-z0-9]+\.(pdf|doc|docx)$/i;

function contentType(ext: string) {
  if (ext === ".pdf") return "application/pdf";
  if (ext === ".doc") return "application/msword";
  if (ext === ".docx") return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
  return "application/octet-stream";
}

/**
 * Serves resume files saved under /tmp on serverless (Vercel).
 * Filenames are generated by /api/career-jobs/apply and must match SAFE_NAME.
 */
export async function GET(req: NextRequest) {
  const name = req.nextUrl.searchParams.get("name") || "";
  const base = path.basename(name);
  if (!SAFE_NAME.test(base)) {
    return NextResponse.json({ message: "Invalid file" }, { status: 400 });
  }

  const dir = path.resolve(path.join(os.tmpdir(), "jiocoder-resumes"));
  const full = path.resolve(dir, base);
  if (!full.startsWith(dir + path.sep) && full !== dir) {
    return NextResponse.json({ message: "Invalid path" }, { status: 400 });
  }

  try {
    const buf = await readFile(full);
    const ext = path.extname(base).toLowerCase();
    return new NextResponse(buf, {
      status: 200,
      headers: {
        "Content-Type": contentType(ext),
        "Content-Disposition": `inline; filename="${base}"`,
        "Cache-Control": "private, max-age=3600",
      },
    });
  } catch {
    return NextResponse.json({ message: "Not found" }, { status: 404 });
  }
}
